services:
  # reverse-proxy:
  #   image: traefik:v3.6
  #   privileged: true
  #   command:
  #     # Basic Networking Proxy
  #     - "--providers.docker=true"
  #     - "--entrypoints.web.address=:80"
  #     - "--providers.docker.exposedbydefault=false"
  #     # HTTPS
  #     - "--entryPoints.websecure.address=:443"
  #     - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
  #     - "--certificatesresolvers.myresolver.acme.email=hello@missalounas.fi"
  #     - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
  #     # Redirecting HTTP request to HTTPS
  #     - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  #     - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  #
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #     - "8080:8080"
  #
  #   volumes:
  #     - letsencrypt:/letsencrypt
  #     - /var/run/docker.sock:/var/run/docker.sock

  dbmate:
    image: amacneil/dbmate:2.34.1
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}?sslmode=disable
    volumes:
      - ./db/migrations:/db/migrations:Z
    networks:
      - dokploy-network
    depends_on:
      db:
        condition: service_healthy
    command: ["--wait", "--migrations-dir", "./db/migrations", "up"]

  db:
    image: postgres:18.1
    container_name: prod-missalounas-db
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - missalounas_prod:/var/lib/postgresql
    ports:
      - "5433:5432"
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # docker-proxy:
  #   image: tecnativa/docker-socket-proxy:latest
  #   privileged: true
  #   environment:
  #     CONTAINERS: 1
  #     EXEC: 1
  #     EVENTS: 1
  #     PING: 1
  #     VERSION: 1
  #     POST: 1
  #   networks:
  #     - docker-socket
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - backend
      # - docker-proxy
    ports:
      - "127.0.0.1:8090:8090"
    command: daemon --docker
    # environment:
    #   DOCKER_HOST: tcp://docker-proxy:2375
    networks:
      - dokploy-network
      # - docker-socket

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.fetch-new-menu.schedule: "@every 30m"
      ofelia.job-exec.fetch-new-menu.command: "uv run python -m src.scraper.engine"
      ofelia.job-exec.fetch-new-menu.no-overlap: "true"
    command: sh -c "uv run python -m src.scraper.engine && uv run uvicorn src.api.main:app --host 0.0.0.0 --port $BACKEND_PORT"
    ports:
      - "$BACKEND_PORT:$BACKEND_PORT"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      dbmate:
        condition: service_completed_successfully
    networks:
      - dokploy-network
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./backend/uv.lock

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.rule=Host(`missalounas.fi`)"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.services.app.loadbalancer.server.port=$FRONTEND_PORT"
    ports:
      - "$FRONTEND_PORT:$FRONTEND_PORT"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - dokploy-network
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .svelte-kit/
            - build/
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/deno.lock

volumes:
  missalounas_prod:
  # letsencrypt:

networks:
  dokploy-network:
    external: true
  # docker-socket:
  #   driver: bridge
